// REGISTER AUTH
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "kai4",
    "password": "1234"
}

###
// Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "kai",
    "password": "1234"
}

###
//CREATE COURSE
POST http://localhost:5000/api/courses
Content-Type: application/json
// Authorization: Bearer Access-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzBlZWRiOGQ4N2M2ZmUzMGE5Mzc3ZmUiLCJpYXQiOjE2NjIwMTIwMTV9.nSaIQBfUuWMWkVeQlCjyqPCf378fyVPj_FpgyaKKXf0


{
    "name":"HTML5",
    "description":"html tutorial",
    "videoId":"MnpVdM0d8UI",
    "status":"LEARNING"
}

###
// GET ALL COURSES OF USER LOGIN
GET http://localhost:5000/api/courses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzBlZTQ2YjVkNTVmYTYzYzMwNGJjM2MiLCJpYXQiOjE2NjQ0MjIzMzV9.9Q1bw40IJzRhEK9mMAavGkj0jmjrLrHBmRJov0QhQ6g

###
// GET COURSE
GET http://localhost:5000/api/courses/learn/63971dca52fb580307ed7054
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mzk3MWM0MTUyZmI1ODAzMDdlZDcwNGIiLCJpYXQiOjE2NzA4NDc3ODF9.lf6L-Jytcs87yTTqF0NWXg5dHeOaDfzBH7oZSZzwGn0

###
// UPDATE COURSE
PUT http://localhost:5000/api/courses/631048e0a65cb538a2d6a271
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzBlZTQ2YjVkNTVmYTYzYzMwNGJjM2MiLCJpYXQiOjE2NjIwMTUyMzV9.tiFkvpSYBh2vLPf0Jw12ceI8HkbRtyhjLtviwaC29co

{
    "name": "Design patterns",
    "description": "VUi VOI JAVASCRIPT",
    "videoId": "l84-JRQ95V4",
    "status": "TO LEARN"
}

###
// DELETE course
DELETE http://localhost:5000/api/courses/631049c850c0212e84b33b2c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzBlZTQ2YjVkNTVmYTYzYzMwNGJjM2MiLCJpYXQiOjE2NjIwMjA3MzF9.Q8JofCVvXVXy00s2m9aY75eU7yxv6qu_TF25NgqJpr4

 